{% set name = "uncompresspy" %}
{% set version = "0.4.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/uncompresspy-{{ version }}.tar.gz
  sha256: e79ead66eaed8d42364d807c0ba3f3a8aef0e0087a9beaf1a60f23a808a6c147

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - uncompresspy
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://pypi.org/project/uncompresspy/
  summary: Pure Python package for uncompressing LZW files (.Z), such as the ones created by Unix's shell tool compress
  dev_url: https://github.com/kYwzor/uncompresspy
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kYwzor
